import type { SpeciesKey } from './utils';

// Map common breeds to a *suggested* avatar index from AVATARS[species]
export const BREED_DEFAULTS: Record<SpeciesKey, Record<string, number>> = {
  dog: {
    'labrador': 3,
    'golden retriever': 3,
    'german shepherd': 4,
    'poodle': 2,
    'beagle': 6,
    'bulldog': 5,
    'spaniel': 7,
    'terrier': 5,
    'small': 0,
    'medium': 1,
    'large': 2,
  },
  cat: {
    'siamese': 5,
    'persian': 1,
    'maine coon': 2,
    'tabby': 2,
    'black': 3,
    'white': 4,
    'calico': 6,
    'shorthair': 0,
    'longhair': 1,
  },
  bird: {
    'budgie': 0,
    'parakeet': 7,
    'parrot': 1,
    'cockatiel': 2,
    'canary': 3,
    'dove': 4,
    'finch': 6,
    'lovebird': 5,
  },
  rabbit: {
    'lop': 1,
    'dutch': 2,
    'lionhead': 3,
    'rex': 4,
    'netherland': 5,
    'flemish': 6,
    'mini': 0,
  },
  hamster: {
    'syrian': 0,
    'dwarf': 1,
    'campbell': 2,
    'roborovski': 3,
    'winter white': 4,
    'chinese': 5,
    'teddy': 6,
    'panda': 7,
  },
  'guinea-pig': {
    'american': 0,
    'abyssinian': 1,
    'peruvian': 2,
    'silkie': 3,
    'teddy': 4,
    'crested': 5,
    'texel': 6,
    'coronet': 7,
  },
  reptile: {
    'gecko': 0,
    'bearded': 1,
    'chameleon': 2,
    'iguana': 3,
    'turtle': 4,
    'tortoise': 5,
    'corn snake': 6,
    'ball python': 7,
  },
  fish: {
    'goldfish': 0,
    'betta': 1,
    'guppy': 2,
    'tetra': 3,
  },
  exotic: {},
};
